export const STRINGS = {
  ready: 'Ready.',
  loading: 'Loading…',
  forging: 'Forging the passage…',
  annotating: 'Annotating your text…',
  stopped: 'Stopped.',
  cancelled: 'Cancelled.',
  audioCleared: 'Audio cleared.',
  coverageComplete: 'Fully covered.',
  nothingToPatch: 'Already fully covered, nothing to patch.',
  passageEnd: 'End of the passage. Record yourself and compare with yesterday.',
  pasteFirst: 'Paste your English text first.',
  emptyBox: 'That box is empty.',
  notJson: 'That is not valid JSON.',
  missingSentences: 'The JSON has no sentences array.',
  noSentencesFound: 'No sentences could be split out of that text.',
  promptCopied: 'Prompt copied. Paste it into any LLM.',
  clipboardBlocked: 'Clipboard blocked — the prompt is in the box below, copy it yourself.',
  missingKey: 'No API key yet — open ⚙ to paste one.',
  loadedWithoutIpa: 'Text loaded. No IPA yet — add a key in ⚙, or use "Copy prompt" in the detour section.',
  forgeTask: 'Forging the passage',
  annotateTask: 'Annotating your text',
  audioTask: 'Generating audio',
  myText: 'My text',
  nothingScheduled: 'Nothing in the pool',
  profileNeedsName: 'Give the profile a name first.',
  lastProfile: 'That is the only profile — keep at least one.',
  alreadyDone: 'Already marked done today.',
  noScheduledItem: 'Nothing scheduled to mark done.',
  poolInstalled: 'Pool installed.',
  poolRejected: 'That pool was rejected.',
  starterMissing: 'Could not load the built-in pool.',

  todayOption: (title: string) => `Today · ${title}`,
  markedDone: (title: string) => `Marked done: ${title}`,
  profileSwitched: (name: string) => `Now drilling as ${name}.`,
  profileExported: (name: string) => `Exported ${name}'s progress.`,
  profileImported: (name: string) => `Imported ${name}'s progress.`,
  yourTurn: (index: number) => `⟳ Your turn — read over sentence ${index + 1}`,
  generatingSentence: (index: number) => `Generating audio for sentence ${index + 1}…`,
  savedTo: (theme: string) => `Saved: ${theme}`,
  opened: (theme: string) => `Opened: ${theme}`,
  forged: (theme: string, words: number) => `Done: ${theme} · ${words} words`,
  annotated: (words: number) => `Done: ${words} words`,
  loaded: (theme: string, words: number) => `Loaded: ${theme} · ${words} words`,
  audioDone: (done: number, total: number) => `Finished ${done}/${total} sentences.`,
  failed: (message: string) => `Error: ${message}`,
  coverageGaps: (missing: string[]) => `Missing: ${missing.join(' ')}`,
  auditSummary: (words: number, sentences: number, missing: number, total: number) =>
    `${words} words · ${sentences} sentences · missing ${missing}/${total} sounds.`,
  migrated: (profiles: number) => `Brought ${profiles} profile${profiles === 1 ? '' : 's'} over from the old version.`,
} as const
