export const STRINGS = {
  ready: 'Ready.',
  forging: 'Forging the passage…',
  annotating: 'Annotating your text…',
  stopped: 'Stopped.',
  cancelled: 'Cancelled.',
  audioCleared: 'Audio cleared.',
  backToPreset: 'Back to the Beatles passage.',
  coverageComplete: 'Fully covered.',
  nothingToPatch: 'Already fully covered, nothing to patch.',
  passageEnd: 'End of the passage. Record yourself and compare with yesterday.',
  pasteFirst: 'Paste your English text first.',
  emptyBox: 'That box is empty.',
  notJson: 'That is not valid JSON.',
  missingSentences: 'The JSON has no sentences array.',
  noSentencesFound: 'No sentences could be split out of that text.',
  promptCopied: 'Prompt copied. Paste it into any LLM.',
  clipboardBlocked: 'Clipboard blocked — the prompt is in the box below, copy it yourself.',
  missingKey: 'No API key yet — open ⚙ to paste one.',
  storageBlocked: 'Could not save (browser storage is blocked).',
  loadedWithoutIpa: 'Text loaded. No IPA yet — add a key in ⚙, or use "Copy prompt" in the detour section.',
  forgeTask: 'Forging the passage',
  annotateTask: 'Annotating your text',
  audioTask: 'Generating audio',

  yourTurn: (index: number) => `⟳ Your turn — read over sentence ${index + 1}`,
  generatingSentence: (index: number) => `Generating audio for sentence ${index + 1}…`,
  savedTo: (theme: string) => `Saved: ${theme}`,
  opened: (theme: string) => `Opened: ${theme}`,
  forged: (theme: string, words: number) => `Done: ${theme} · ${words} words`,
  annotated: (words: number) => `Done: ${words} words`,
  loaded: (theme: string, words: number) => `Loaded: ${theme} · ${words} words`,
  audioDone: (done: number, total: number) => `Finished ${done}/${total} sentences.`,
  failed: (message: string) => `Error: ${message}`,
  coverageGaps: (missing: string[]) => `Missing: ${missing.join(' ')}`,
  auditSummary: (words: number, sentences: number, missing: number, total: number) =>
    `${words} words · ${sentences} sentences · missing ${missing}/${total} sounds.`,
  myText: 'My text',
} as const
